-- Local-only harness that mimics the parts of a Supabase project the
-- KogiQuest migration depends on. NOT for production: Supabase already
-- provides all of this. Used by `npm run test:db`.

-- Roles Supabase creates for you.
do $$
begin
    if not exists (select 1 from pg_roles where rolname = 'anon') then
        create role anon nologin;
    end if;
    if not exists (select 1 from pg_roles where rolname = 'authenticated') then
        create role authenticated nologin;
    end if;
    if not exists (select 1 from pg_roles where rolname = 'service_role') then
        create role service_role nologin bypassrls;
    end if;
end;
$$;

grant usage on schema public to anon, authenticated, service_role;

-- Minimal auth schema.
create schema if not exists auth;

create table if not exists auth.users (
    id    uuid primary key default gen_random_uuid(),
    email text
);

-- Supabase reads the subject out of the request JWT claims. Locally we set
-- the same GUC by hand to impersonate a signed-in player.
create or replace function auth.uid()
returns uuid
language sql
stable
as $$
    select nullif(
        nullif(current_setting('request.jwt.claims', true), '')::json ->> 'sub',
        ''
    )::uuid;
$$;

grant usage on schema auth to anon, authenticated, service_role;
grant execute on function auth.uid() to anon, authenticated, service_role;
grant select on auth.users to service_role;

-- Stand-in for the pre-existing table that belongs to another application.
-- Production already has this. It exists here only so the test suite can
-- assert that the KogiQuest migration leaves it completely alone.
create table if not exists public.question_suggestions (
    id               bigint generated by default as identity primary key,
    created_at       timestamptz not null default now(),
    question_id      text,
    user_id          text,
    suggested_answer text,
    user_comment     text,
    status           text default 'pending'
);
