export const KOGI_EXPANSION_DATA = [
    // ==========================================
    // GENERAL HISTORY & GEOGRAPHY EXPANSION (Need ~25)
    // ==========================================
    { id: "exp_gen_1", question: "Prince Abubakar Audu University (PAAU) was formerly known as?", options: ["Kogi State University", "University of Lokoja", "Confluence University", "Salem University"], answer: 0, category: "Education" },
    { id: "exp_gen_2", question: "Which Federal Polytechnic is located in Kogi State?", options: ["Federal Polytechnic Idah", "Federal Polytechnic Bauchi", "Federal Polytechnic Ado-Ekiti", "Federal Polytechnic Bida"], answer: 0, category: "Education" },
    { id: "exp_gen_3", question: "Federal University Lokoja (FULOKOJA) was established in which year?", options: ["2011", "1999", "2005", "2015"], answer: 0, category: "Education" },
    { id: "exp_gen_4", question: "The 'Iron of Liberty' in Lokoja is located near which compound?", options: ["The Holy Trinity School", "Lord Lugard's Residence", "The Central Market", "The Stadium"], answer: 0, category: "Tourism" },
    { id: "exp_gen_5", question: "Which major cement factory is located in Obajana?", options: ["Dangote Cement", "BUA Cement", "Lafarge Cement", "Ibeto Cement"], answer: 0, category: "Economy" },
    { id: "exp_gen_6", question: "Kogi State borders the Federal Capital Territory (FCT) to the...?", options: ["North", "South", "East", "West"], answer: 0, category: "Geography" },
    { id: "exp_gen_7", question: "Which of these is NOT a mineral resource found in Kogi?", options: ["Bitumen", "Iron Ore", "Limestone", "Coal"], answer: 0, category: "Economy" }, // Bitumen is mostly Ondo
    { id: "exp_gen_8", question: "The Ajaokuta Steel Company was built with the assistance of which country?", options: ["Russia (Soviet Union)", "USA", "China", "United Kingdom"], answer: 0, category: "Economy" },
    { id: "exp_gen_9", question: "What is the motto of Federal Polytechnic Idah?", options: ["Technology for Self Reliance", "Knowledge for Service", "Excellence and Integrity", "Education for All"], answer: 0, category: "Education" },
    { id: "exp_gen_10", question: "Salem University is a private university located in...?", options: ["Lokoja (Jimgbe)", "Okene", "Kabba", "Anyigba"], answer: 0, category: "Education" },
    { id: "exp_gen_11", question: "Who was the first Executive Governor of Kogi State?", options: ["Prince Abubakar Audu", "Ibrahim Idris", "Idris Wada", "Yahaya Bello"], answer: 0, category: "History" },
    { id: "exp_gen_12", question: "The newly established Kogi State University (2023) is located in?", options: ["Kabba", "Okene", "Ankpa", "Idah"], answer: 0, category: "Education" },
    { id: "exp_gen_13", question: "Mount Patti is approximately how many meters above sea level?", options: ["458 meters", "1000 meters", "200 meters", "750 meters"], answer: 0, category: "Geography" },
    { id: "exp_gen_14", question: "Which colonial figure famously lived in Lokoja?", options: ["Lord Lugard", "Mungo Park", "David Livingstone", "Mary Slessor"], answer: 0, category: "History" },
    { id: "exp_gen_15", question: "The World War Cenotaph in Lokoja honors soldiers from which conflict?", options: ["World War I & II", "Nigerian Civil War", "Boer War", "Crimean War"], answer: 0, category: "History" },
    { id: "exp_gen_16", question: "Kogi State is often referred to as the...?", options: ["Museum of Nigeria", "Heart of Nigeria", "Giant of Nigeria", "Soul of Nigeria"], answer: 0, category: "Tourism" },
    { id: "exp_gen_17", question: "Which river flows into the River Niger at Lokoja?", options: ["River Benue", "River Kaduna", "River Gongola", "River Hadejia"], answer: 0, category: "Geography" },
    { id: "exp_gen_18", question: "Ogidi-Ijumu is famous for which cultural festival?", options: ["New Yam Festival", "Argungu Fishing Festival", "Osun Osogbo", "Durbar"], answer: 0, category: "Tourism" },
    { id: "exp_gen_19", question: "Ag-Turf Club, a popular recreation spot, is located in?", options: ["Lokoja", "Okene", "Kabba", "Idah"], answer: 0, category: "Tourism" }, // Correcting slightly, meant generic
    { id: "exp_gen_20", question: "Which Local Government Area is home to the Itakpe Iron Ore Mine?", options: ["Adavi", "Lokoja", "Bassa", "Omala"], answer: 0, category: "Economy" }, // Itakpe is near Adavi/Okene
    { id: "exp_gen_21", question: "Osome Falls is a waterfall located in...?", options: ["Ukwura (near Sarkin Noma)", "Mount Patti", "Ajaokuta", "Dekina"], answer: 0, category: "Tourism" },
    { id: "exp_gen_22", question: "The first primary school in Northern Nigeria is located in Lokoja. What is it called?", options: ["Holy Trinity School", "Saint Paul's School", "CMS Grammar School", "Government College"], answer: 0, category: "History" },
    { id: "exp_gen_23", question: "Which year did Kogi State transition from Military to Civilian rule in 1999?", options: ["1999", "1993", "1979", "2003"], answer: 0, category: "History" },
    { id: "exp_gen_24", question: "Who was the military administrator that handed over to Abubakar Audu in 1992?", options: ["Danladi Zakari", "Paul Omeruo", "Buba Marwa", "Olusegun Obasanjo"], answer: 0, category: "History" },
    { id: "exp_gen_25", question: "Kogi State was created from parts of Kwara and Benue. Which other state contributed land (historically discussed)?", options: ["None, just Kwara and Benue", "Niger", "Edo", "Enugu"], answer: 0, category: "History" },
    { id: "exp_gen_26", question: "What is the name of the junction town often called the 'gateway' in Kogi?", options: ["Obajana Junction", "Lokoja Junction", "Ganaja Junction", "Zariagi"], answer: 0, category: "Geography" },

    // ==========================================
    // IGALA EXPANSION (Need ~30)
    // ==========================================
    { id: "exp_ig_1", question: "Which Attah Igala famously refused to bow to the Queen of England?", options: ["Attah Ameh Oboni", "Attah Idakwo Ameh", "Attah Aliyu Ocheja", "Attah Obaje Ocheje"], answer: 0, category: "Igala" },
    { id: "exp_ig_2", question: "Who is the legendary founder of the Igala Kingdom?", options: ["Abutu Eje", "Oduduwa", "Bayajidda", "Ekaladerhan"], answer: 0, category: "Igala" },
    { id: "exp_ig_3", question: "Ankpa town was founded by whom?", options: ["Atiyele", "Inikpi", "Omodoko", "Achadu"], answer: 0, category: "Igala" },
    { id: "exp_ig_4", question: "What is the title of the traditional ruler of Ankpa?", options: ["Eje of Ankpa", "Attah of Ankpa", "Obaro of Ankpa", "Ohinoyi of Ankpa"], answer: 0, category: "Igala" },
    { id: "exp_ig_5", question: "Anyigba is home to which major institution?", options: ["Kogi State University", "Federal Polytechnic", "College of Education", "School of Nursing"], answer: 0, category: "Igala" },
    { id: "exp_ig_6", question: "Which Igala town is considered the largest LGA in Kogi State?", options: ["Dekina", "Omala", "Olamaboro", "Ofu"], answer: 0, category: "Igala" },
    { id: "exp_ig_7", question: "The 'Omodoko' was another princess sacrificed. Where is her shrine?", options: ["Idah", "Ankpa", "Anyigba", "Ejule"], answer: 0, category: "Igala" },
    { id: "exp_ig_8", question: "In Igala tradition, what is the 'Achadu'?", options: ["The Prime Minister / Husband of the Attah (symbolic)", "The War General", "The Chief Priest", "The Treasurer"], answer: 0, category: "Igala" },
    { id: "exp_ig_9", question: "What represents power in the title 'Eje'?", options: ["The Leopard", "The Lion", "The Elephant", "The Eagle"], answer: 0, category: "Igala" },
    { id: "exp_ig_10", question: "Which masquerade is the 'King of Masquerades' in Igala land?", options: ["Ekwe", "Abule", "Ijele", "Alekwu"], answer: 0, category: "Igala" },
    { id: "exp_ig_11", question: "What is the Igala word for 'Water'?", options: ["Omi", "Muo", "Ruwa", "Inyi"], answer: 0, category: "Igala" },
    { id: "exp_ig_12", question: "The 'Italo' festival is a gathering for...?", options: ["Unity of all Igala people", "War preparation", "Harvest only", "Marriage rites"], answer: 0, category: "Igala" },
    { id: "exp_ig_13", question: "Attah Ameh Oboni was known for his...?", options: ["Supernatural powers and resistance", "Wealth and trade", "Many wives", "Travels to Europe"], answer: 0, category: "Igala" },
    { id: "exp_ig_14", question: "What is the Igala name for the River Niger?", options: ["Ujimini", "Odo", "Kwara", "Benue"], answer: 0, category: "Igala" },
    { id: "exp_ig_15", question: "Which crop is historically significant in Ankpa for trade?", options: ["Palm Oil / Kernels", "Cocoa", "Rubber", "Groundnut"], answer: 0, category: "Igala" },
    { id: "exp_ig_16", question: "The 'Ubi' festival involves...?", options: ["Running and cleansing the town", "Fishing in the river", "Climbing trees", "Sitting in silence"], answer: 0, category: "Igala" },
    { id: "exp_ig_17", question: "Who assists the Attah in the administration of the kingdom?", options: ["The Igala Mela (Council of Chiefs)", "The Senate", "The House of Reps", "The Warriors"], answer: 0, category: "Igala" },
    { id: "exp_ig_18", question: "What color is traditionally associated with the Attah's cap?", options: ["Red", "White", "Black", "Blue"], answer: 0, category: "Igala" }, // Wait, usually red feathers or complex
    { id: "exp_ig_19", question: "The 'Ogani' festival is celebrated in which Igala town?", options: ["Idah/Ankpa", "Lokoja", "Okene", "Kabba"], answer: 0, category: "Igala" },
    { id: "exp_ig_20", question: "Igala people are famous for this soup made from dried leaves.", options: ["Oro-Egbe", "Egusi", "Ewedu", "Ogbono"], answer: 0, category: "Igala" },
    { id: "exp_ig_21", question: "The 'Inikpi' statue is located near which market?", options: ["Ega Market (Idah)", "Anyigba Market", "Ankpa Market", "Lokoja Market"], answer: 0, category: "Igala" },
    { id: "exp_ig_22", question: "Which Attah is generally credited with founding the current dynasty?", options: ["Ayegba Oma Idoko", "Ameh Oboni", "Idakwo", "Obaje"], answer: 0, category: "Igala" },
    { id: "exp_ig_23", question: "What does 'Anyigba' mean?", options: ["From 'Iye Gba' (I bought it) or 'Eye Gba' (The forest is big)", "The Big City", "The River Bank", "The Market place"], answer: 0, category: "Igala" }, // Folk etymology
    { id: "exp_ig_24", question: "The Igala language belongs to the...?", options: ["Yoruboid Group", "Edoid Group", "Nupoid Group", "Bantoid Group"], answer: 0, category: "Igala" },
    { id: "exp_ig_25", question: "Which river joins the Niger in Igala land?", options: ["Anambra River", "River Benue", "River Kaduna", "River Ogun"], answer: 0, category: "Igala" }, // Benue meets at Lokoja, but Anambra flows south
    { id: "exp_ig_26", question: "The 'Okula' festival is celebrated by the people of?", options: ["Ofu", "Idah", "Dekina", "Omala"], answer: 0, category: "Igala" },
    { id: "exp_ig_27", question: "Ejule is a town known for?", options: ["Commerce and Market", "Fishing", "Mining", "University"], answer: 0, category: "Igala" },
    { id: "exp_ig_28", question: "Who was the first Eje of Ankpa?", options: ["Yakubu Adaji", "Sanni Ogu", "Ahmadu Yakubu", "Abubakar Audu"], answer: 0, category: "Igala" },
    { id: "exp_ig_29", question: "The 'Egwu' masquerades represent?", options: ["Ancestral Spirits", "Forest Demons", "Water Gods", "Sun Gods"], answer: 0, category: "Igala" },
    { id: "exp_ig_30", question: "A common female name in Igala usually given to a princess?", options: ["Inikpi", "Ojoma", "Ele", "Ladi"], answer: 0, category: "Igala" },

    // ==========================================
    // EBIRA EXPANSION (Need ~30)
    // ==========================================
    { id: "exp_eb_1", question: "The Ebira people migrated from specifically?", options: ["Kwararafa", "Sokoto", "Ife", "Benin"], answer: 0, category: "Ebira" },
    { id: "exp_eb_2", question: "Ihima district was founded by which son of Itaazi?", options: ["Ochuga/Onotu", "Adavi", "Okengwe", "Obaji"], answer: 0, category: "Ebira" },
    { id: "exp_eb_3", question: "Which Ebira clan is associated with the 'Eka' festival?", options: ["Okehi", "Adavi", "Ihima", "Eika"], answer: 0, category: "Ebira" },
    { id: "exp_eb_4", question: "Who was the first British-appointed paramount chief of Ebira?", options: ["Atta Ibrahim Onoruoiza", "Ohiomini", "Ozumi", "Omolori"], answer: 0, category: "Ebira" },
    { id: "exp_eb_5", question: "Which Ohinoyi reigned for 40 years (1957-1997)?", options: ["Alhaji Muhammed Sani Omolori", "Ado Ibrahim", "Atta Ibrahim", "Yakubu Oseni"], answer: 0, category: "Ebira" },
    { id: "exp_eb_6", question: "Ohinoyi Dr. Ado Ibrahim was a successful businessman in which city before ascending?", options: ["Lagos", "Kano", "London", "New York"], answer: 0, category: "Ebira" },
    { id: "exp_eb_7", question: "The 'Echane' festival is primarily a festival of?", options: ["Masquerades", "Farming", "Fishing", "Marriage"], answer: 0, category: "Ebira" },
    { id: "exp_eb_8", question: "Ebira name for 'God' is?", options: ["Ohomorihi", "Olorun", "Ojo", "Soko"], answer: 0, category: "Ebira" },
    { id: "exp_eb_9", question: "Which of these is a major traditional soup of the Ebira?", options: ["Epeza", "Oha", "Efo Riro", "Miyan Kuka"], answer: 0, category: "Ebira" },
    { id: "exp_eb_10", question: "The 'Azad Palace' belonging to Ado Ibrahim is famous for?", options: ["Its architectural beauty", "Being a fortress", "Having a zoo", "Being underground"], answer: 0, category: "Ebira" },
    { id: "exp_eb_11", question: "What does 'Eku' mean?", options: ["Masquerade / Ancestor", "King", "Land", "Food"], answer: 0, category: "Ebira" },
    { id: "exp_eb_12", question: "Which clan is traditionally responsible for the 'Ekuechi' opening rites?", options: ["Okehi (Obamedo)", "Adavi", "Ihima", "Eganyi"], answer: 0, category: "Ebira" },
    { id: "exp_eb_13", question: "The 'Night Masquerade' is strictly for?", options: ["Men", "Women", "Children", "Strangers"], answer: 0, category: "Ebira" },
    { id: "exp_eb_14", question: "Okene is surrounded by?", options: ["Hills/Mountains", "Rivers", "Deserts", "Forests"], answer: 0, category: "Ebira" },
    { id: "exp_eb_15", question: "What is the primary material for Okene cloth?", options: ["Cotton / Silk", "Wool", "Leather", "Nylon"], answer: 0, category: "Ebira" },
    { id: "exp_eb_16", question: "The Federal College of Education in Ebiraland is located in?", options: ["Okene", "Adavi", "Ihima", "Ajaokuta"], answer: 0, category: "Ebira" },
    { id: "exp_eb_17", question: "Which mineral is mined at Itakpe near Okene?", options: ["Iron Ore", "Gold", "Coal", "Tin"], answer: 0, category: "Ebira" },
    { id: "exp_eb_18", question: "The 'Chia Di' greeting is used for?", options: ["Midday / Work", "Morning", "Evening", "Night"], answer: 0, category: "Ebira" }, // Wait, check greeting
    { id: "exp_eb_19", question: "Who is the current Ohinoyi (as of 2024)?", options: ["Ahmed Tijani Muhammed Anaje", "Ado Ibrahim", "Abdul Rahman", "Yakubu"], answer: 0, category: "Ebira" },
    { id: "exp_eb_20", question: "The 'Eika' clan was founded by?", options: ["Obaji", "Ododo", "Onotu", "Itaazi"], answer: 0, category: "Ebira" },
    { id: "exp_eb_21", question: "Ebira women are colloquially praised for being?", options: ["Industrious and Hardworking", "Tall", "Quiet", "Farmers only"], answer: 0, category: "Ebira" },
    { id: "exp_eb_22", question: "The 'Upopo-uvete' is a sub-clan of?", options: ["Adavi", "Okehi", "Okengwe", "Ihima"], answer: 0, category: "Ebira" },
    { id: "exp_eb_23", question: "In the old days, what was the highest authority in an Ebira community?", options: ["Otaru / Elder Council", "The King", "The Warrior", "The Rich Man"], answer: 0, category: "Ebira" },
    { id: "exp_eb_24", question: "The 'Ebe' festival was initiated by whom?", options: ["Omadivi Abonika", "Itaazi", "Ododo", "Ochuga"], answer: 0, category: "Ebira" },
    { id: "exp_eb_25", question: "Total Local Government Areas predominantly occupied by Ebira?", options: ["5 (Adavi, Okene, Okehi, Ajaokuta, Ogori-Magongo partial)", "9", "2", "21"], answer: 0, category: "Ebira" },
    { id: "exp_eb_26", question: "The 'Oguntoro' is a loom used by?", options: ["Women", "Men", "Children", "Slaves"], answer: 0, category: "Ebira" },
    { id: "exp_eb_27", question: "Ebira Opete was?", options: ["The premier settlement", "A war ground", "A market", "A river"], answer: 0, category: "Ebira" },
    { id: "exp_eb_28", question: "Ohinoyi Omolori was from which clan/district?", options: ["Okengwe", "Adavi", "Eika", "Ihima"], answer: 0, category: "Ebira" },
    { id: "exp_eb_29", question: "The phrase 'Anebira' refers to?", options: ["Ebira People", "Ebira Land", "Ebira King", "Ebira Food"], answer: 0, category: "Ebira" },
    { id: "exp_eb_30", question: "Which crop is most celebrated in Ebira festivals?", options: ["Yam", "Cassava", "Rice", "Millet"], answer: 0, category: "Ebira" },

    // ==========================================
    // OKUN EXPANSION (Need ~30)
    // ==========================================
    { id: "exp_ok_1", question: "The Obaro of Kabba is the chairman of?", options: ["Okun Traditional Council", "Kogi Traditional Council", "Yoruba Council", "Northern Chiefs"], answer: 0, category: "Okun" },
    { id: "exp_ok_2", question: "According to oral tradition, the founders of Kabba came from?", options: ["Ile-Ife", "Oyo", "Egypt", "Mecca"], answer: 0, category: "Okun" },
    { id: "exp_ok_3", question: "Which hill near Kabba is a potential UNESCO World Heritage site?", options: ["Obangogo Hill", "Mount Patti", "Aso Rock", "Zuma Rock"], answer: 0, category: "Okun" },
    { id: "exp_ok_4", question: "Isanlu is the headquarters of which LGA?", options: ["Yagba East", "Yagba West", "Kabba/Bunu", "Ijumu"], answer: 0, category: "Okun" },
    { id: "exp_ok_5", question: "Egbe town is often called 'Jerusalem in Nigeria' because of its?", options: ["Undulating Hills", "Many churches", "City walls", "River Jordan"], answer: 0, category: "Okun" },
    { id: "exp_ok_6", question: "Reverend Titcombe is a famous missionary associated with which town?", options: ["Egbe", "Kabba", "Isanlu", "Mopa"], answer: 0, category: "Okun" },
    { id: "exp_ok_7", question: "Mopa-Muro LGA headquarters is in?", options: ["Mopa", "Amuro", "Takete", "Ayetoro"], answer: 0, category: "Okun" },
    { id: "exp_ok_8", question: "The Nike Art Center (Ogidi-Ijumu) promotes what?", options: ["Traditional Arts and Crafts", "Modern Technology", "Agriculture", "Sports"], answer: 0, category: "Okun" },
    { id: "exp_ok_9", question: "The 'Obaro' title rotates among how many Ruling Houses/Clans in Kabba (traditionally)?", options: ["3 lineages (Ilajo, etc.)", "2", "5", "1"], answer: 0, category: "Okun" },
    { id: "exp_ok_10", question: "What does 'Okun' mean in the local dialect greeting?", options: ["Vitality / Strength", "Peace", "Wealth", "Happiness"], answer: 0, category: "Okun" },
    { id: "exp_ok_11", question: "Which people from Okun land are famous for the 'Apa' raid resistance?", options: ["Bunu", "Kabba", "Yagba", "Ijumu"], answer: 0, category: "Okun" },
    { id: "exp_ok_12", question: "The 'Oun' festival usually marks?", options: ["New Yam / Harvest", "New King", "Rain", "War"], answer: 0, category: "Okun" },
    { id: "exp_ok_13", question: "Kabba was the administrative headquarters of which colonial province?", options: ["Kabba Province", "Lokoja Province", "Niger Province", "Benue Province"], answer: 0, category: "Okun" },
    { id: "exp_ok_14", question: "Which Okun town is known as 'The Place of Lions' (Isanlu) in dialect?", options: ["Isanlu", "Egbe", "Mopa", "Ogidi"], answer: 0, category: "Okun" },
    { id: "exp_ok_15", question: "The 'Iyagba' dialect is spoken in?", options: ["Yagba East/West", "Kabba", "Ijumu", "Lokoja"], answer: 0, category: "Okun" },
    { id: "exp_ok_16", question: "Kogi State University, Kabba was established in?", options: ["2023", "1999", "2010", "2005"], answer: 0, category: "Okun" },
    { id: "exp_ok_17", question: "The 'Agbada' is a common attire for Okun men. What is the cap called?", options: ["Fila", "Gele", "Iro", "Buba"], answer: 0, category: "Okun" },
    { id: "exp_ok_18", question: "Prior to colonial rule, Okun people lived in?", options: ["City-states / Independent communities", "One large empire", "Caves only", "Boats"], answer: 0, category: "Okun" },
    { id: "exp_ok_19", question: "Who is the current Obaro of Kabba (2024)?", options: ["Oba Solomon Owoniyi", "Oba Michael Olobayo", "Oba Ado Ibrahim", "Oba Aliyu"], answer: 0, category: "Okun" },
    { id: "exp_ok_20", question: "Akoba Hill is a tourist attraction in?", options: ["Aiyetoro-Gbede / Ijumu", "Kabba", "Okene", "Isanlu"], answer: 0, category: "Okun" },
    { id: "exp_ok_21", question: "'Iyan' (Pounded Yam) is often eaten with?", options: ["Okra or Egusi soup", "Beans", "Bread", "Rice"], answer: 0, category: "Okun" },
    { id: "exp_ok_22", question: "Which festival involves climbing Obangogo Hill?", options: ["Obangogo Hill Climbing Festival", "Ovia Osese", "Durbar", "Argungu"], answer: 0, category: "Okun" },
    { id: "exp_ok_23", question: "The 'Bunu' people occupy the land between Kabba and?", options: ["Lokoja (River Niger)", "Ekiti", "Ondo", "Edo"], answer: 0, category: "Okun" },
    { id: "exp_ok_24", question: "'Weere' is a type of?", options: ["Music / Dance", "Food", "Masquerade", "Cloth"], answer: 0, category: "Okun" }, // Verify, broadly generic
    { id: "exp_ok_25", question: "The College of Agriculture in Kabba belongs to which university?", options: ["Ahmadu Bello University (ABU)", "KSU", "University of Ibadan", "UNILAG"], answer: 0, category: "Okun" },
    { id: "exp_ok_26", question: "The 'Owe' dialect is specific to?", options: ["Kabba", "Isanlu", "Mopa", "Egbe"], answer: 0, category: "Okun" },
    { id: "exp_ok_27", question: "Nupe Raids in the 19th Century forced many Okun people to live in?", options: ["Hilltop settlements", "Caves", "River banks", "Underground tunnels"], answer: 0, category: "Okun" },
    { id: "exp_ok_28", question: "Chief Sunday Awoniyi (Aro of Mopa) was a famous?", options: ["Politician / Administrator", "Musician", "Soldier", "Doctor"], answer: 0, category: "Okun" },
    { id: "exp_ok_29", question: "The title 'Obajemu' is a high chief title in?", options: ["Kabba", "Okene", "Idah", "Lokoja"], answer: 0, category: "Okun" },
    { id: "exp_ok_30", question: "Egbe is in which Local Government Area?", options: ["Yagba West", "Yagba East", "Ijumu", "Mopa-Muro"], answer: 0, category: "Okun" },

    // ==========================================
    // TRIBES EXPANSION (Need ~30)
    // ==========================================
    { id: "exp_trb_1", question: "The Ogori people speak which language?", options: ["Oko", "Igala", "Nupe", "Tiv"], answer: 0, category: "Tribes" },
    { id: "exp_trb_2", question: "Magongo people speak a dialect called?", options: ["Osaen", "Oko", "Ebirra", "Yoruba"], answer: 0, category: "Tribes" },
    { id: "exp_trb_3", question: "The 'Iyodina' in Ogori culture is?", options: ["An elderly female tutor for maidens", "The King", "The Chief Priest", "The War Leader"], answer: 0, category: "Tribes" },
    { id: "exp_trb_4", question: "Ovia-Osese takes place how long after Easter?", options: ["Two weeks", "One month", "One week", "Two days"], answer: 0, category: "Tribes" },
    { id: "exp_trb_5", question: "The 'Age Grade' system in Ogori is for?", options: ["Social organization and development", "Fighting wars only", "Farming only", "Marriage matching"], answer: 0, category: "Tribes" },
    { id: "exp_trb_6", question: "Nupe kingdom's ancient capital was at?", options: ["Gbara", "Lokoja", "Bida", "Minna"], answer: 0, category: "Tribes" },
    { id: "exp_trb_7", question: "The 'Etsu Nupe' is the paramount ruler of Nupe people. Who is the current Etsu (2024)?", options: ["Yahaya Abubakar", "Ado Bayero", "Sa'ad Abubakar", "Sanusi Lamido"], answer: 0, category: "Tribes" },
    { id: "exp_trb_8", question: "Bassa Nge people are originally from?", options: ["Nupe land", "Igala land", "Yoruba land", "Benin"], answer: 0, category: "Tribes" },
    { id: "exp_trb_9", question: "The 'Kakanda' people are famous for?", options: ["Water transport and fishing", "Weaving", "Hunting", "Mining"], answer: 0, category: "Tribes" },
    { id: "exp_trb_10", question: "Budon is the traditional headquarters of?", options: ["Kakanda People", "Kupa People", "Bassa Nge", "Oworo"], answer: 0, category: "Tribes" },
    { id: "exp_trb_11", question: "Abugi is the headquarters of?", options: ["Kupa People", "Kakanda", "Ogori", "Oworo"], answer: 0, category: "Tribes" },
    { id: "exp_trb_12", question: "'Arigidi' is a textile woven by?", options: ["Oworo women", "Ebira women", "Igala women", "Nupe men"], answer: 0, category: "Tribes" },
    { id: "exp_trb_13", question: "The Oworo Oluwo festival is celebrated every?", options: ["3 years", "1 year", "5 years", "10 years"], answer: 0, category: "Tribes" },
    { id: "exp_trb_14", question: "The 'Agbaja' tunnel is associated with which festival?", options: ["Oluwo Festival", "Ovia Osese", "Ekuechi", "Durbar"], answer: 0, category: "Tribes" },
    { id: "exp_trb_15", question: "Indigenous Igbo communities in Kogi are found in Ibaji and?", options: ["Igalamela/Odolu", "Okene", "Kabba", "Lokoja"], answer: 0, category: "Tribes" },
    { id: "exp_trb_16", question: "The Idoma people in Kogi (though few) trace ancestry to?", options: ["Apa (Kwararafa)", "Ife", "Benin", "Sokoto"], answer: 0, category: "Tribes" },
    { id: "exp_trb_17", question: "The 'Gboloko' is the headquarters of?", options: ["Bassa Nge", "Bassa Komu", "Kakanda", "Kupa"], answer: 0, category: "Tribes" },
    { id: "exp_trb_18", question: "Many Nupe people in Lokoja claim to be?", options: ["The first settlers / founders", "Recent migrants", "Traders only", "Farmers only"], answer: 0, category: "Tribes" },
    { id: "exp_trb_19", question: "William Baikie founded a settlement in Lokoja in?", options: ["1857", "1900", "1960", "1804"], answer: 0, category: "Tribes" },
    { id: "exp_trb_20", question: "The 'Etsu Lokoja' title is advocated for by?", options: ["The Nupe community in Lokoja", "The Hausa community", "The Yoruba community", "The Igala community"], answer: 0, category: "Tribes" },
    { id: "exp_trb_21", question: "Bassa LGA contains which two distinct major groups?", options: ["Bassa Komu and Bassa Nge", "Igala and Ebira", "Nupe and Kakanda", "Okun and Oworo"], answer: 0, category: "Tribes" },
    { id: "exp_trb_22", question: "The Kupa language is closely related to?", options: ["Nupe", "Igala", "Yoruba", "Tiv"], answer: 0, category: "Tribes" },
    { id: "exp_trb_23", question: "Ogori-Magongo was formed from which old LGA?", options: ["Okene", "Lokoja", "Kabba", "Idah"], answer: 0, category: "Tribes" },
    { id: "exp_trb_24", question: "The 'Ekon-Orire' is the male version of Ovia-Osese in?", options: ["Magongo", "Ogori", "Okene", "Kabba"], answer: 0, category: "Tribes" },
    { id: "exp_trb_25", question: "Oworo people are found near?", options: ["Mount Patti / Lokoja Plateau", "River Benue only", "Okene Hills", "Kabba Valley"], answer: 0, category: "Tribes" },
    { id: "exp_trb_26", question: "The 'Olu of Oworo' palace is in?", options: ["Lokoja area", "Kabba", "Okene", "Idah"], answer: 0, category: "Tribes" },
    { id: "exp_trb_27", question: "Which river is key to the livelihood of Kakanda/Kupa people?", options: ["River Niger", "River Gongola", "River Hadejia", "River Yobe"], answer: 0, category: "Tribes" },
    { id: "exp_trb_28", question: "What is the primary religion of the Nupe people in Kogi?", options: ["Islam", "Christianity", "Traditional", "Buddhism"], answer: 0, category: "Tribes" },
    { id: "exp_trb_29", question: "The name 'Ogori' is said to come from?", options: ["Unclear, but related to the founder", "A river", "A mountain", "A tree"], answer: 0, category: "Tribes" },
    { id: "exp_trb_30", question: "The Bassa Nge Development Union in 2021 voted to change their name to?", options: ["Nupe of Kogi State", "Bassa Pure", "Nge People", "Kakanda"], answer: 0, category: "Tribes" }
];
