export const KOGI_EXPANSION_DATA = [
    // ==========================================
    // GENERAL HISTORY & GEOGRAPHY EXPANSION (Need ~25)
    // ==========================================
    { id: "exp_gen_1", question: "Prince Abubakar Audu University (PAAU) was formerly known as?", options: ["Confluence University", "Salem University", "Kogi State University", "University of Lokoja"], answer: 2, category: "Education" },
    { id: "exp_gen_2", question: "Which Federal Polytechnic is located in Kogi State?", options: ["Federal Polytechnic Ado-Ekiti", "Federal Polytechnic Idah", "Federal Polytechnic Bida", "Federal Polytechnic Bauchi"], answer: 1, category: "Education" },
    { id: "exp_gen_3", question: "Federal University Lokoja (FULOKOJA) was established in which year?", options: ["2011", "2005", "1999", "2015"], answer: 0, category: "Education" },
    { id: "exp_gen_4", question: "The 'Iron of Liberty' in Lokoja is located near which compound?", options: ["The Stadium", "Lord Lugard's Residence", "The Central Market", "The Holy Trinity School"], answer: 3, category: "Tourism" },
    { id: "exp_gen_5", question: "Which major cement factory is located in Obajana?", options: ["BUA Cement", "Ibeto Cement", "Lafarge Cement", "Dangote Cement"], answer: 3, category: "Economy" },
    { id: "exp_gen_6", question: "Kogi State borders the Federal Capital Territory (FCT) to the...?", options: ["East", "North", "West", "South"], answer: 1, category: "Geography" },
    { id: "exp_gen_7", question: "Which of these is NOT a mineral resource found in Kogi?", options: ["Coal", "Bitumen", "Limestone", "Iron Ore"], answer: 1, category: "Economy" }, // Bitumen is mostly Ondo
    { id: "exp_gen_8", question: "The Ajaokuta Steel Company was built with the assistance of which country?", options: ["United Kingdom", "USA", "Russia (Soviet Union)", "China"], answer: 2, category: "Economy" },
    { id: "exp_gen_9", question: "What is the motto of Federal Polytechnic Idah?", options: ["Education for All", "Knowledge for Service", "Technology for Self Reliance", "Excellence and Integrity"], answer: 2, category: "Education" },
    { id: "exp_gen_10", question: "Salem University is a private university located in...?", options: ["Okene", "Lokoja (Jimgbe)", "Anyigba", "Kabba"], answer: 1, category: "Education" },
    { id: "exp_gen_11", question: "Who was the first Executive Governor of Kogi State?", options: ["Prince Abubakar Audu", "Ibrahim Idris", "Yahaya Bello", "Idris Wada"], answer: 0, category: "History" },
    { id: "exp_gen_12", question: "The newly established Kogi State University (2023) is located in?", options: ["Idah", "Okene", "Ankpa", "Kabba"], answer: 3, category: "Education" },
    { id: "exp_gen_13", question: "Mount Patti is approximately how many meters above sea level?", options: ["1000 meters", "200 meters", "750 meters", "458 meters"], answer: 3, category: "Geography" },
    { id: "exp_gen_14", question: "Which colonial figure famously lived in Lokoja?", options: ["Lord Lugard", "Mungo Park", "Mary Slessor", "David Livingstone"], answer: 0, category: "History" },
    { id: "exp_gen_15", question: "The World War Cenotaph in Lokoja honors soldiers from which conflict?", options: ["Crimean War", "Nigerian Civil War", "World War I & II", "Boer War"], answer: 2, category: "History" },
    { id: "exp_gen_16", question: "Kogi State is often referred to as the...?", options: ["Heart of Nigeria", "Museum of Nigeria", "Giant of Nigeria", "Soul of Nigeria"], answer: 1, category: "Tourism" },
    { id: "exp_gen_17", question: "Which river flows into the River Niger at Lokoja?", options: ["River Benue", "River Kaduna", "River Gongola", "River Hadejia"], answer: 0, category: "Geography" },
    { id: "exp_gen_18", question: "Ogidi-Ijumu is famous for which cultural festival?", options: ["Durbar", "New Yam Festival", "Osun Osogbo", "Argungu Fishing Festival"], answer: 1, category: "Tourism" },
    { id: "exp_gen_19", question: "Ag-Turf Club, a popular recreation spot, is located in?", options: ["Okene", "Idah", "Lokoja", "Kabba"], answer: 2, category: "Tourism" }, // Correcting slightly, meant generic
    { id: "exp_gen_20", question: "Which Local Government Area is home to the Itakpe Iron Ore Mine?", options: ["Bassa", "Lokoja", "Adavi", "Omala"], answer: 2, category: "Economy" }, // Itakpe is near Adavi/Okene
    { id: "exp_gen_21", question: "Osome Falls is a waterfall located in...?", options: ["Dekina", "Mount Patti", "Ajaokuta", "Ukwura (near Sarkin Noma)"], answer: 3, category: "Tourism" },
    { id: "exp_gen_22", question: "The first primary school in Northern Nigeria is located in Lokoja. What is it called?", options: ["Saint Paul's School", "Government College", "CMS Grammar School", "Holy Trinity School"], answer: 3, category: "History" },
    { id: "exp_gen_23", question: "Which year did Kogi State transition from Military to Civilian rule in 1999?", options: ["1979", "1999", "2003", "1993"], answer: 1, category: "History" },
    { id: "exp_gen_24", question: "Who was the military administrator that handed over to Abubakar Audu in 1992?", options: ["Paul Omeruo", "Olusegun Obasanjo", "Buba Marwa", "Danladi Zakari"], answer: 3, category: "History" },
    { id: "exp_gen_25", question: "Kogi State was created from parts of Kwara and Benue. Which other state contributed land (historically discussed)?", options: ["Enugu", "None, just Kwara and Benue", "Niger", "Edo"], answer: 1, category: "History" },
    { id: "exp_gen_26", question: "What is the name of the junction town often called the 'gateway' in Kogi?", options: ["Obajana Junction", "Lokoja Junction", "Zariagi", "Ganaja Junction"], answer: 0, category: "Geography" },

    // ==========================================
    // IGALA EXPANSION (Need ~30)
    // ==========================================
    { id: "exp_ig_1", question: "Which Attah Igala famously refused to bow to the Queen of England?", options: ["Attah Obaje Ocheje", "Attah Aliyu Ocheja", "Attah Idakwo Ameh", "Attah Ameh Oboni"], answer: 3, category: "Igala" },
    { id: "exp_ig_2", question: "Who is the legendary founder of the Igala Kingdom?", options: ["Abutu Eje", "Oduduwa", "Bayajidda", "Ekaladerhan"], answer: 0, category: "Igala" },
    { id: "exp_ig_3", question: "Ankpa town was founded by whom?", options: ["Omodoko", "Atiyele", "Achadu", "Inikpi"], answer: 1, category: "Igala" },
    { id: "exp_ig_4", question: "What is the title of the traditional ruler of Ankpa?", options: ["Ohinoyi of Ankpa", "Eje of Ankpa", "Obaro of Ankpa", "Attah of Ankpa"], answer: 1, category: "Igala" },
    { id: "exp_ig_5", question: "Anyigba is home to which major institution?", options: ["Federal Polytechnic", "College of Education", "School of Nursing", "Kogi State University"], answer: 3, category: "Igala" },
    { id: "exp_ig_6", question: "Which Igala town is considered the largest LGA in Kogi State?", options: ["Dekina", "Olamaboro", "Ofu", "Omala"], answer: 0, category: "Igala" },
    { id: "exp_ig_7", question: "The 'Omodoko' was another princess sacrificed. Where is her shrine?", options: ["Idah", "Ejule", "Anyigba", "Ankpa"], answer: 0, category: "Igala" },
    { id: "exp_ig_8", question: "In Igala tradition, what is the 'Achadu'?", options: ["The War General", "The Chief Priest", "The Treasurer", "The Prime Minister / Husband of the Attah (symbolic)"], answer: 3, category: "Igala" },
    { id: "exp_ig_9", question: "What represents power in the title 'Eje'?", options: ["The Eagle", "The Elephant", "The Lion", "The Leopard"], answer: 3, category: "Igala" },
    { id: "exp_ig_10", question: "Which masquerade is the 'King of Masquerades' in Igala land?", options: ["Ijele", "Abule", "Ekwe", "Alekwu"], answer: 2, category: "Igala" },
    { id: "exp_ig_11", question: "What is the Igala word for 'Water'?", options: ["Inyi", "Omi", "Ruwa", "Muo"], answer: 1, category: "Igala" },
    { id: "exp_ig_12", question: "The 'Italo' festival is a gathering for...?", options: ["Harvest only", "War preparation", "Unity of all Igala people", "Marriage rites"], answer: 2, category: "Igala" },
    { id: "exp_ig_13", question: "Attah Ameh Oboni was known for his...?", options: ["Many wives", "Supernatural powers and resistance", "Wealth and trade", "Travels to Europe"], answer: 1, category: "Igala" },
    { id: "exp_ig_14", question: "What is the Igala name for the River Niger?", options: ["Odo", "Ujimini", "Kwara", "Benue"], answer: 1, category: "Igala" },
    { id: "exp_ig_15", question: "Which crop is historically significant in Ankpa for trade?", options: ["Groundnut", "Palm Oil / Kernels", "Rubber", "Cocoa"], answer: 1, category: "Igala" },
    { id: "exp_ig_16", question: "The 'Ubi' festival involves...?", options: ["Climbing trees", "Sitting in silence", "Fishing in the river", "Running and cleansing the town"], answer: 3, category: "Igala" },
    { id: "exp_ig_17", question: "Who assists the Attah in the administration of the kingdom?", options: ["The Igala Mela (Council of Chiefs)", "The Senate", "The Warriors", "The House of Reps"], answer: 0, category: "Igala" },
    { id: "exp_ig_18", question: "What color is traditionally associated with the Attah's cap?", options: ["White", "Blue", "Black", "Red"], answer: 3, category: "Igala" }, // Wait, usually red feathers or complex
    { id: "exp_ig_19", question: "The 'Ogani' festival is celebrated in which Igala town?", options: ["Kabba", "Idah/Ankpa", "Okene", "Lokoja"], answer: 1, category: "Igala" },
    { id: "exp_ig_20", question: "Igala people are famous for this soup made from dried leaves.", options: ["Ewedu", "Ogbono", "Oro-Egbe", "Egusi"], answer: 2, category: "Igala" },
    { id: "exp_ig_21", question: "The 'Inikpi' statue is located near which market?", options: ["Ankpa Market", "Ega Market (Idah)", "Anyigba Market", "Lokoja Market"], answer: 1, category: "Igala" },
    { id: "exp_ig_22", question: "Which Attah is generally credited with founding the current dynasty?", options: ["Ayegba Oma Idoko", "Ameh Oboni", "Obaje", "Idakwo"], answer: 0, category: "Igala" },
    { id: "exp_ig_23", question: "What does 'Anyigba' mean?", options: ["The Market place", "The River Bank", "From 'Iye Gba' (I bought it) or 'Eye Gba' (The forest is big)", "The Big City"], answer: 2, category: "Igala" }, // Folk etymology
    { id: "exp_ig_24", question: "The Igala language belongs to the...?", options: ["Nupoid Group", "Edoid Group", "Bantoid Group", "Yoruboid Group"], answer: 3, category: "Igala" },
    { id: "exp_ig_25", question: "Which river joins the Niger in Igala land?", options: ["River Ogun", "River Kaduna", "Anambra River", "River Benue"], answer: 2, category: "Igala" }, // Benue meets at Lokoja, but Anambra flows south
    { id: "exp_ig_26", question: "The 'Okula' festival is celebrated by the people of?", options: ["Dekina", "Omala", "Idah", "Ofu"], answer: 3, category: "Igala" },
    { id: "exp_ig_27", question: "Ejule is a town known for?", options: ["Mining", "Fishing", "University", "Commerce and Market"], answer: 3, category: "Igala" },
    { id: "exp_ig_28", question: "Who was the first Eje of Ankpa?", options: ["Yakubu Adaji", "Abubakar Audu", "Sanni Ogu", "Ahmadu Yakubu"], answer: 0, category: "Igala" },
    { id: "exp_ig_29", question: "The 'Egwu' masquerades represent?", options: ["Ancestral Spirits", "Forest Demons", "Sun Gods", "Water Gods"], answer: 0, category: "Igala" },
    { id: "exp_ig_30", question: "A common female name in Igala usually given to a princess?", options: ["Inikpi", "Ojoma", "Ele", "Ladi"], answer: 0, category: "Igala" },

    // ==========================================
    // EBIRA EXPANSION (Need ~30)
    // ==========================================
    { id: "exp_eb_1", question: "The Ebira people migrated from specifically?", options: ["Benin", "Ife", "Kwararafa", "Sokoto"], answer: 2, category: "Ebira" },
    { id: "exp_eb_2", question: "Ihima district was founded by which son of Itaazi?", options: ["Ochuga/Onotu", "Obaji", "Okengwe", "Adavi"], answer: 0, category: "Ebira" },
    { id: "exp_eb_3", question: "Which Ebira clan is associated with the 'Eka' festival?", options: ["Eika", "Okehi", "Adavi", "Ihima"], answer: 1, category: "Ebira" },
    { id: "exp_eb_4", question: "Who was the first British-appointed paramount chief of Ebira?", options: ["Ohiomini", "Omolori", "Ozumi", "Atta Ibrahim Onoruoiza"], answer: 3, category: "Ebira" },
    { id: "exp_eb_5", question: "Which Ohinoyi reigned for 40 years (1957-1997)?", options: ["Yakubu Oseni", "Atta Ibrahim", "Ado Ibrahim", "Alhaji Muhammed Sani Omolori"], answer: 3, category: "Ebira" },
    { id: "exp_eb_6", question: "Ohinoyi Dr. Ado Ibrahim was a successful businessman in which city before ascending?", options: ["London", "Kano", "Lagos", "New York"], answer: 2, category: "Ebira" },
    { id: "exp_eb_7", question: "The 'Echane' festival is primarily a festival of?", options: ["Farming", "Fishing", "Marriage", "Masquerades"], answer: 3, category: "Ebira" },
    { id: "exp_eb_8", question: "Ebira name for 'God' is?", options: ["Ojo", "Soko", "Olorun", "Ohomorihi"], answer: 3, category: "Ebira" },
    { id: "exp_eb_9", question: "Which of these is a major traditional soup of the Ebira?", options: ["Oha", "Epeza", "Efo Riro", "Miyan Kuka"], answer: 1, category: "Ebira" },
    { id: "exp_eb_10", question: "The 'Azad Palace' belonging to Ado Ibrahim is famous for?", options: ["Being underground", "Being a fortress", "Its architectural beauty", "Having a zoo"], answer: 2, category: "Ebira" },
    { id: "exp_eb_11", question: "What does 'Eku' mean?", options: ["King", "Masquerade / Ancestor", "Food", "Land"], answer: 1, category: "Ebira" },
    { id: "exp_eb_12", question: "Which clan is traditionally responsible for the 'Ekuechi' opening rites?", options: ["Okehi (Obamedo)", "Adavi", "Eganyi", "Ihima"], answer: 0, category: "Ebira" },
    { id: "exp_eb_13", question: "The 'Night Masquerade' is strictly for?", options: ["Men", "Strangers", "Women", "Children"], answer: 0, category: "Ebira" },
    { id: "exp_eb_14", question: "Okene is surrounded by?", options: ["Hills/Mountains", "Deserts", "Forests", "Rivers"], answer: 0, category: "Ebira" },
    { id: "exp_eb_15", question: "What is the primary material for Okene cloth?", options: ["Nylon", "Cotton / Silk", "Leather", "Wool"], answer: 1, category: "Ebira" },
    { id: "exp_eb_16", question: "The Federal College of Education in Ebiraland is located in?", options: ["Okene", "Ihima", "Ajaokuta", "Adavi"], answer: 0, category: "Ebira" },
    { id: "exp_eb_17", question: "Which mineral is mined at Itakpe near Okene?", options: ["Tin", "Coal", "Iron Ore", "Gold"], answer: 2, category: "Ebira" },
    { id: "exp_eb_18", question: "The 'Chia Di' greeting is used for?", options: ["Midday / Work", "Evening", "Night", "Morning"], answer: 0, category: "Ebira" }, // Wait, check greeting
    { id: "exp_eb_19", question: "Who is the current Ohinoyi (as of 2024)?", options: ["Abdul Rahman", "Ahmed Tijani Muhammed Anaje", "Ado Ibrahim", "Yakubu"], answer: 1, category: "Ebira" },
    { id: "exp_eb_20", question: "The 'Eika' clan was founded by?", options: ["Itaazi", "Obaji", "Onotu", "Ododo"], answer: 1, category: "Ebira" },
    { id: "exp_eb_21", question: "Ebira women are colloquially praised for being?", options: ["Quiet", "Tall", "Industrious and Hardworking", "Farmers only"], answer: 2, category: "Ebira" },
    { id: "exp_eb_22", question: "The 'Upopo-uvete' is a sub-clan of?", options: ["Okengwe", "Adavi", "Okehi", "Ihima"], answer: 1, category: "Ebira" },
    { id: "exp_eb_23", question: "In the old days, what was the highest authority in an Ebira community?", options: ["The King", "The Rich Man", "The Warrior", "Otaru / Elder Council"], answer: 3, category: "Ebira" },
    { id: "exp_eb_24", question: "The 'Ebe' festival was initiated by whom?", options: ["Itaazi", "Ochuga", "Omadivi Abonika", "Ododo"], answer: 2, category: "Ebira" },
    { id: "exp_eb_25", question: "Total Local Government Areas predominantly occupied by Ebira?", options: ["2", "5 (Adavi, Okene, Okehi, Ajaokuta, Ogori-Magongo partial)", "9", "21"], answer: 1, category: "Ebira" },
    { id: "exp_eb_26", question: "The 'Oguntoro' is a loom used by?", options: ["Women", "Slaves", "Children", "Men"], answer: 0, category: "Ebira" },
    { id: "exp_eb_27", question: "Ebira Opete was?", options: ["A market", "A war ground", "A river", "The premier settlement"], answer: 3, category: "Ebira" },
    { id: "exp_eb_28", question: "Ohinoyi Omolori was from which clan/district?", options: ["Adavi", "Eika", "Ihima", "Okengwe"], answer: 3, category: "Ebira" },
    { id: "exp_eb_29", question: "The phrase 'Anebira' refers to?", options: ["Ebira Land", "Ebira People", "Ebira King", "Ebira Food"], answer: 1, category: "Ebira" },
    { id: "exp_eb_30", question: "Which crop is most celebrated in Ebira festivals?", options: ["Yam", "Millet", "Cassava", "Rice"], answer: 0, category: "Ebira" },

    // ==========================================
    // OKUN EXPANSION (Need ~30)
    // ==========================================
    { id: "exp_ok_1", question: "The Obaro of Kabba is the chairman of?", options: ["Okun Traditional Council", "Kogi Traditional Council", "Northern Chiefs", "Yoruba Council"], answer: 0, category: "Okun" },
    { id: "exp_ok_2", question: "According to oral tradition, the founders of Kabba came from?", options: ["Oyo", "Egypt", "Ile-Ife", "Mecca"], answer: 2, category: "Okun" },
    { id: "exp_ok_3", question: "Which hill near Kabba is a potential UNESCO World Heritage site?", options: ["Mount Patti", "Aso Rock", "Zuma Rock", "Obangogo Hill"], answer: 3, category: "Okun" },
    { id: "exp_ok_4", question: "Isanlu is the headquarters of which LGA?", options: ["Yagba East", "Kabba/Bunu", "Ijumu", "Yagba West"], answer: 0, category: "Okun" },
    { id: "exp_ok_5", question: "Egbe town is often called 'Jerusalem in Nigeria' because of its?", options: ["River Jordan", "Many churches", "City walls", "Undulating Hills"], answer: 3, category: "Okun" },
    { id: "exp_ok_6", question: "Reverend Titcombe is a famous missionary associated with which town?", options: ["Egbe", "Mopa", "Kabba", "Isanlu"], answer: 0, category: "Okun" },
    { id: "exp_ok_7", question: "Mopa-Muro LGA headquarters is in?", options: ["Amuro", "Takete", "Mopa", "Ayetoro"], answer: 2, category: "Okun" },
    { id: "exp_ok_8", question: "The Nike Art Center (Ogidi-Ijumu) promotes what?", options: ["Traditional Arts and Crafts", "Modern Technology", "Agriculture", "Sports"], answer: 0, category: "Okun" },
    { id: "exp_ok_9", question: "The 'Obaro' title rotates among how many Ruling Houses/Clans in Kabba (traditionally)?", options: ["1", "5", "2", "3 lineages (Ilajo, etc.)"], answer: 3, category: "Okun" },
    { id: "exp_ok_10", question: "What does 'Okun' mean in the local dialect greeting?", options: ["Happiness", "Vitality / Strength", "Wealth", "Peace"], answer: 1, category: "Okun" },
    { id: "exp_ok_11", question: "Which people from Okun land are famous for the 'Apa' raid resistance?", options: ["Yagba", "Bunu", "Ijumu", "Kabba"], answer: 1, category: "Okun" },
    { id: "exp_ok_12", question: "The 'Oun' festival usually marks?", options: ["New Yam / Harvest", "New King", "Rain", "War"], answer: 0, category: "Okun" },
    { id: "exp_ok_13", question: "Kabba was the administrative headquarters of which colonial province?", options: ["Benue Province", "Lokoja Province", "Niger Province", "Kabba Province"], answer: 3, category: "Okun" },
    { id: "exp_ok_14", question: "Which Okun town is known as 'The Place of Lions' (Isanlu) in dialect?", options: ["Egbe", "Mopa", "Isanlu", "Ogidi"], answer: 2, category: "Okun" },
    { id: "exp_ok_15", question: "The 'Iyagba' dialect is spoken in?", options: ["Kabba", "Ijumu", "Lokoja", "Yagba East/West"], answer: 3, category: "Okun" },
    { id: "exp_ok_16", question: "Kogi State University, Kabba was established in?", options: ["2010", "2023", "1999", "2005"], answer: 1, category: "Okun" },
    { id: "exp_ok_17", question: "The 'Agbada' is a common attire for Okun men. What is the cap called?", options: ["Gele", "Fila", "Buba", "Iro"], answer: 1, category: "Okun" },
    { id: "exp_ok_18", question: "Prior to colonial rule, Okun people lived in?", options: ["Caves only", "City-states / Independent communities", "Boats", "One large empire"], answer: 1, category: "Okun" },
    { id: "exp_ok_19", question: "Who is the current Obaro of Kabba (2024)?", options: ["Oba Ado Ibrahim", "Oba Solomon Owoniyi", "Oba Michael Olobayo", "Oba Aliyu"], answer: 1, category: "Okun" },
    { id: "exp_ok_20", question: "Akoba Hill is a tourist attraction in?", options: ["Isanlu", "Kabba", "Aiyetoro-Gbede / Ijumu", "Okene"], answer: 2, category: "Okun" },
    { id: "exp_ok_21", question: "'Iyan' (Pounded Yam) is often eaten with?", options: ["Rice", "Okra or Egusi soup", "Beans", "Bread"], answer: 1, category: "Okun" },
    { id: "exp_ok_22", question: "Which festival involves climbing Obangogo Hill?", options: ["Argungu", "Ovia Osese", "Durbar", "Obangogo Hill Climbing Festival"], answer: 3, category: "Okun" },
    { id: "exp_ok_23", question: "The 'Bunu' people occupy the land between Kabba and?", options: ["Ekiti", "Lokoja (River Niger)", "Edo", "Ondo"], answer: 1, category: "Okun" },
    { id: "exp_ok_24", question: "'Weere' is a type of?", options: ["Cloth", "Music / Dance", "Masquerade", "Food"], answer: 1, category: "Okun" }, // Verify, broadly generic
    { id: "exp_ok_25", question: "The College of Agriculture in Kabba belongs to which university?", options: ["KSU", "Ahmadu Bello University (ABU)", "UNILAG", "University of Ibadan"], answer: 1, category: "Okun" },
    { id: "exp_ok_26", question: "The 'Owe' dialect is specific to?", options: ["Kabba", "Mopa", "Isanlu", "Egbe"], answer: 0, category: "Okun" },
    { id: "exp_ok_27", question: "Nupe Raids in the 19th Century forced many Okun people to live in?", options: ["Underground tunnels", "Caves", "River banks", "Hilltop settlements"], answer: 3, category: "Okun" },
    { id: "exp_ok_28", question: "Chief Sunday Awoniyi (Aro of Mopa) was a famous?", options: ["Soldier", "Politician / Administrator", "Musician", "Doctor"], answer: 1, category: "Okun" },
    { id: "exp_ok_29", question: "The title 'Obajemu' is a high chief title in?", options: ["Kabba", "Idah", "Okene", "Lokoja"], answer: 0, category: "Okun" },
    { id: "exp_ok_30", question: "Egbe is in which Local Government Area?", options: ["Mopa-Muro", "Yagba West", "Ijumu", "Yagba East"], answer: 1, category: "Okun" },

    // ==========================================
    // TRIBES EXPANSION (Need ~30)
    // ==========================================
    { id: "exp_trb_1", question: "The Ogori people speak which language?", options: ["Oko", "Tiv", "Igala", "Nupe"], answer: 0, category: "Tribes" },
    { id: "exp_trb_2", question: "Magongo people speak a dialect called?", options: ["Oko", "Osaen", "Yoruba", "Ebirra"], answer: 1, category: "Tribes" },
    { id: "exp_trb_3", question: "The 'Iyodina' in Ogori culture is?", options: ["The War Leader", "The Chief Priest", "The King", "An elderly female tutor for maidens"], answer: 3, category: "Tribes" },
    { id: "exp_trb_4", question: "Ovia-Osese takes place how long after Easter?", options: ["One week", "Two weeks", "Two days", "One month"], answer: 1, category: "Tribes" },
    { id: "exp_trb_5", question: "The 'Age Grade' system in Ogori is for?", options: ["Social organization and development", "Farming only", "Fighting wars only", "Marriage matching"], answer: 0, category: "Tribes" },
    { id: "exp_trb_6", question: "Nupe kingdom's ancient capital was at?", options: ["Minna", "Lokoja", "Gbara", "Bida"], answer: 2, category: "Tribes" },
    { id: "exp_trb_7", question: "The 'Etsu Nupe' is the paramount ruler of Nupe people. Who is the current Etsu (2024)?", options: ["Ado Bayero", "Yahaya Abubakar", "Sanusi Lamido", "Sa'ad Abubakar"], answer: 1, category: "Tribes" },
    { id: "exp_trb_8", question: "Bassa Nge people are originally from?", options: ["Benin", "Igala land", "Nupe land", "Yoruba land"], answer: 2, category: "Tribes" },
    { id: "exp_trb_9", question: "The 'Kakanda' people are famous for?", options: ["Water transport and fishing", "Hunting", "Weaving", "Mining"], answer: 0, category: "Tribes" },
    { id: "exp_trb_10", question: "Budon is the traditional headquarters of?", options: ["Bassa Nge", "Kakanda People", "Kupa People", "Oworo"], answer: 1, category: "Tribes" },
    { id: "exp_trb_11", question: "Abugi is the headquarters of?", options: ["Kakanda", "Kupa People", "Oworo", "Ogori"], answer: 1, category: "Tribes" },
    { id: "exp_trb_12", question: "'Arigidi' is a textile woven by?", options: ["Nupe men", "Oworo women", "Ebira women", "Igala women"], answer: 1, category: "Tribes" },
    { id: "exp_trb_13", question: "The Oworo Oluwo festival is celebrated every?", options: ["3 years", "5 years", "1 year", "10 years"], answer: 0, category: "Tribes" },
    { id: "exp_trb_14", question: "The 'Agbaja' tunnel is associated with which festival?", options: ["Ovia Osese", "Ekuechi", "Durbar", "Oluwo Festival"], answer: 3, category: "Tribes" },
    { id: "exp_trb_15", question: "Indigenous Igbo communities in Kogi are found in Ibaji and?", options: ["Kabba", "Igalamela/Odolu", "Okene", "Lokoja"], answer: 1, category: "Tribes" },
    { id: "exp_trb_16", question: "The Idoma people in Kogi (though few) trace ancestry to?", options: ["Sokoto", "Apa (Kwararafa)", "Ife", "Benin"], answer: 1, category: "Tribes" },
    { id: "exp_trb_17", question: "The 'Gboloko' is the headquarters of?", options: ["Bassa Komu", "Kakanda", "Kupa", "Bassa Nge"], answer: 3, category: "Tribes" },
    { id: "exp_trb_18", question: "Many Nupe people in Lokoja claim to be?", options: ["Recent migrants", "The first settlers / founders", "Traders only", "Farmers only"], answer: 1, category: "Tribes" },
    { id: "exp_trb_19", question: "William Baikie founded a settlement in Lokoja in?", options: ["1900", "1857", "1960", "1804"], answer: 1, category: "Tribes" },
    { id: "exp_trb_20", question: "The 'Etsu Lokoja' title is advocated for by?", options: ["The Hausa community", "The Yoruba community", "The Nupe community in Lokoja", "The Igala community"], answer: 2, category: "Tribes" },
    { id: "exp_trb_21", question: "Bassa LGA contains which two distinct major groups?", options: ["Bassa Komu and Bassa Nge", "Okun and Oworo", "Igala and Ebira", "Nupe and Kakanda"], answer: 0, category: "Tribes" },
    { id: "exp_trb_22", question: "The Kupa language is closely related to?", options: ["Igala", "Tiv", "Nupe", "Yoruba"], answer: 2, category: "Tribes" },
    { id: "exp_trb_23", question: "Ogori-Magongo was formed from which old LGA?", options: ["Kabba", "Okene", "Lokoja", "Idah"], answer: 1, category: "Tribes" },
    { id: "exp_trb_24", question: "The 'Ekon-Orire' is the male version of Ovia-Osese in?", options: ["Ogori", "Magongo", "Kabba", "Okene"], answer: 1, category: "Tribes" },
    { id: "exp_trb_25", question: "Oworo people are found near?", options: ["Kabba Valley", "Okene Hills", "River Benue only", "Mount Patti / Lokoja Plateau"], answer: 3, category: "Tribes" },
    { id: "exp_trb_26", question: "The 'Olu of Oworo' palace is in?", options: ["Okene", "Lokoja area", "Idah", "Kabba"], answer: 1, category: "Tribes" },
    { id: "exp_trb_27", question: "Which river is key to the livelihood of Kakanda/Kupa people?", options: ["River Hadejia", "River Niger", "River Yobe", "River Gongola"], answer: 1, category: "Tribes" },
    { id: "exp_trb_28", question: "What is the primary religion of the Nupe people in Kogi?", options: ["Buddhism", "Islam", "Christianity", "Traditional"], answer: 1, category: "Tribes" },
    { id: "exp_trb_29", question: "The name 'Ogori' is said to come from?", options: ["Unclear, but related to the founder", "A tree", "A river", "A mountain"], answer: 0, category: "Tribes" },
    { id: "exp_trb_30", question: "The Bassa Nge Development Union in 2021 voted to change their name to?", options: ["Nge People", "Kakanda", "Nupe of Kogi State", "Bassa Pure"], answer: 2, category: "Tribes" }
];
