import fs from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

// Import data files
import { KOGI_DATA } from './src/lib/kogi_data.js';
import { KOGI_POLITICS_DATA } from './src/lib/kogi_politics_data.js';
import { KOGI_PLACES_DATA } from './src/lib/kogi_places_data.js';
import { KOGI_TRIBES_DATA } from './src/lib/kogi_tribes_data.js';
import { KOGI_EXPANSION_DATA } from './src/lib/kogi_expansion_data.js';
import { kogiIndustriesQuestions } from './src/lib/kogi_industries_data.js';
import { kogiCultureGeneralQuestions } from './src/lib/kogi_culture_general_data.js';
import { kogiNotablePeopleQuestions } from './src/lib/kogi_notable_people_data.js';

// Combine all data
const allQuestions = [
    ...KOGI_DATA,
    ...KOGI_POLITICS_DATA,
    ...KOGI_PLACES_DATA,
    ...KOGI_TRIBES_DATA,
    ...KOGI_EXPANSION_DATA,
    ...kogiIndustriesQuestions,
    ...kogiCultureGeneralQuestions,
    ...kogiNotablePeopleQuestions
];

const TABLE_NAME = 'questions';

const schemaSQL = `
-- 1. Create the table
CREATE TABLE IF NOT EXISTS public.${TABLE_NAME} (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    question text NOT NULL,
    options text[] NOT NULL,
    answer integer NOT NULL,
    category text DEFAULT 'General'::text,
    difficulty text DEFAULT 'Medium'::text
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.${TABLE_NAME} ENABLE ROW LEVEL SECURITY;

-- 3. Create Policy (Allow read access to authenticated users only)
CREATE POLICY "Authenticated can read questions" 
ON public.${TABLE_NAME} FOR SELECT 
TO authenticated 
USING (true);

-- 4. Create Policy (Service Role only for inserts/updates - optional safety)
-- 4. Create Policy (Service Role only for inserts/updates - optional safety)
-- Usually implicit, but good to clarify.

-- 5. Create Suggestions Table
CREATE TABLE IF NOT EXISTS public.question_suggestions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    question_id text NOT NULL,
    user_id text,
    suggested_answer text,
    user_comment text,
    status text DEFAULT 'pending'::text
);

-- 6. Enable RLS for Suggestions
ALTER TABLE public.question_suggestions ENABLE ROW LEVEL SECURITY;

-- 7. Policy for Suggestions (Allow insert for all, read for service role/admins)
CREATE POLICY "Enable insert for all users" 
ON public.question_suggestions FOR INSERT 
WITH CHECK (true);

`;

const generateInserts = (questions) => {
    return questions.map(q => {
        // Escape single quotes in text
        const safeQuestion = q.question.replace(/'/g, "''");
        const safeCategory = (q.category || 'General').replace(/'/g, "''");

        // Format options array for SQL: ARRAY['A','B','C']
        const safeOptions = q.options.map(opt => `'${opt.toString().replace(/'/g, "''")}'`).join(',');

        return `INSERT INTO public.${TABLE_NAME} (question, options, answer, category) VALUES ('${safeQuestion}', ARRAY[${safeOptions}], ${q.answer}, '${safeCategory}');`;
    }).join('\n');
};

const finalOutput = schemaSQL + '\n\n-- Data Inserts --\n' + generateInserts(allQuestions);

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const outputPath = join(__dirname, '../supabase_seed.sql');

fs.writeFileSync(outputPath, finalOutput);

console.log(`Successfully generated SQL with ${allQuestions.length} questions at ${outputPath}`);
