-- KogiQuest backend tables.
-- Run this in the Supabase SQL editor (Dashboard -> SQL Editor -> New query -> Run).
-- Without these two tables the Global Leaderboard returns 404 (PGRST205) and both
-- score submission and "Report an issue" fail.

-- ---------------------------------------------------------------------------
-- 1. leaderboard
-- ---------------------------------------------------------------------------
create table if not exists public.leaderboard (
    id          bigint generated by default as identity primary key,
    created_at  timestamptz not null default now(),
    user_id     uuid references auth.users (id) on delete cascade,
    username    text not null default 'Explorer',
    score       integer not null default 0 check (score >= 0),
    level       integer not null default 1 check (level >= 1)
);

create index if not exists leaderboard_score_idx on public.leaderboard (score desc);

alter table public.leaderboard enable row level security;

-- Anyone (including signed-out visitors) may read the top scores.
drop policy if exists "Leaderboard is publicly readable" on public.leaderboard;
create policy "Leaderboard is publicly readable"
    on public.leaderboard for select
    to anon, authenticated
    using (true);

-- A signed-in player may only insert rows for themselves.
drop policy if exists "Players insert their own scores" on public.leaderboard;
create policy "Players insert their own scores"
    on public.leaderboard for insert
    to authenticated
    with check (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- 2. question_suggestions  (backs the "Report an issue" dialog)
-- ---------------------------------------------------------------------------
create table if not exists public.question_suggestions (
    id                bigint generated by default as identity primary key,
    created_at        timestamptz not null default now(),
    question_id       text,
    user_id           uuid references auth.users (id) on delete set null,
    suggested_answer  text,
    user_comment      text,
    status            text not null default 'pending'   -- pending | approved | rejected
);

alter table public.question_suggestions enable row level security;

-- Anyone may file a report; nobody but the service role may read them back.
drop policy if exists "Anyone can report a question" on public.question_suggestions;
create policy "Anyone can report a question"
    on public.question_suggestions for insert
    to anon, authenticated
    with check (true);
